// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: core.sql

package sqlitequery

import (
	"context"
)

const deleteDocument = `-- name: DeleteDocument :execrows
DELETE FROM documents WHERE kind = ?1 AND id = ?2
`

type DeleteDocumentParams struct {
	Kind string `json:"kind"`
	ID   string `json:"id"`
}

func (q *Queries) DeleteDocument(ctx context.Context, arg DeleteDocumentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteDocument, arg.Kind, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteMonitor = `-- name: DeleteMonitor :execrows
DELETE FROM monitors WHERE id = ?1
`

func (q *Queries) DeleteMonitor(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteMonitor, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getDocument = `-- name: GetDocument :one
SELECT payload FROM documents WHERE kind = ?1 AND id = ?2
`

type GetDocumentParams struct {
	Kind string `json:"kind"`
	ID   string `json:"id"`
}

func (q *Queries) GetDocument(ctx context.Context, arg GetDocumentParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getDocument, arg.Kind, arg.ID)
	var payload string
	err := row.Scan(&payload)
	return payload, err
}

const getMonitor = `-- name: GetMonitor :one
SELECT id, config_version, generation, kind, enabled, interval_ms, config_json FROM monitors WHERE id = ?1
`

func (q *Queries) GetMonitor(ctx context.Context, id string) (Monitor, error) {
	row := q.db.QueryRowContext(ctx, getMonitor, id)
	var i Monitor
	err := row.Scan(
		&i.ID,
		&i.ConfigVersion,
		&i.Generation,
		&i.Kind,
		&i.Enabled,
		&i.IntervalMs,
		&i.ConfigJson,
	)
	return i, err
}

const getRuntime = `-- name: GetRuntime :one
SELECT monitor_id, config_version, generation, state, failures, successes, last_round_id, last_collected_at, heartbeat_version, heartbeat_at FROM monitor_runtime WHERE monitor_id = ?1
`

func (q *Queries) GetRuntime(ctx context.Context, monitorID string) (MonitorRuntime, error) {
	row := q.db.QueryRowContext(ctx, getRuntime, monitorID)
	var i MonitorRuntime
	err := row.Scan(
		&i.MonitorID,
		&i.ConfigVersion,
		&i.Generation,
		&i.State,
		&i.Failures,
		&i.Successes,
		&i.LastRoundID,
		&i.LastCollectedAt,
		&i.HeartbeatVersion,
		&i.HeartbeatAt,
	)
	return i, err
}

const listDocuments = `-- name: ListDocuments :many
SELECT payload FROM documents WHERE kind = ?1 ORDER BY id
`

func (q *Queries) ListDocuments(ctx context.Context, kind string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listDocuments, kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var payload string
		if err := rows.Scan(&payload); err != nil {
			return nil, err
		}
		items = append(items, payload)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMonitors = `-- name: ListMonitors :many
SELECT id, config_version, generation, kind, enabled, interval_ms, config_json FROM monitors ORDER BY id
`

func (q *Queries) ListMonitors(ctx context.Context) ([]Monitor, error) {
	rows, err := q.db.QueryContext(ctx, listMonitors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Monitor{}
	for rows.Next() {
		var i Monitor
		if err := rows.Scan(
			&i.ID,
			&i.ConfigVersion,
			&i.Generation,
			&i.Kind,
			&i.Enabled,
			&i.IntervalMs,
			&i.ConfigJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putDocument = `-- name: PutDocument :exec
INSERT INTO documents(kind,id,payload) VALUES(?1,?2,?3)
ON CONFLICT(kind,id) DO UPDATE SET payload=excluded.payload
`

type PutDocumentParams struct {
	Kind    string `json:"kind"`
	ID      string `json:"id"`
	Payload string `json:"payload"`
}

func (q *Queries) PutDocument(ctx context.Context, arg PutDocumentParams) error {
	_, err := q.db.ExecContext(ctx, putDocument, arg.Kind, arg.ID, arg.Payload)
	return err
}

const putMonitor = `-- name: PutMonitor :exec
INSERT INTO monitors(id,config_version,generation,kind,enabled,interval_ms,config_json)
VALUES(?1,?2,?3,?4,?5,?6,?7)
ON CONFLICT(id) DO UPDATE SET config_version=excluded.config_version,generation=excluded.generation,kind=excluded.kind,enabled=excluded.enabled,interval_ms=excluded.interval_ms,config_json=excluded.config_json
`

type PutMonitorParams struct {
	ID            string `json:"id"`
	ConfigVersion int64  `json:"config_version"`
	Generation    int64  `json:"generation"`
	Kind          string `json:"kind"`
	Enabled       int64  `json:"enabled"`
	IntervalMs    int64  `json:"interval_ms"`
	ConfigJson    string `json:"config_json"`
}

func (q *Queries) PutMonitor(ctx context.Context, arg PutMonitorParams) error {
	_, err := q.db.ExecContext(ctx, putMonitor,
		arg.ID,
		arg.ConfigVersion,
		arg.Generation,
		arg.Kind,
		arg.Enabled,
		arg.IntervalMs,
		arg.ConfigJson,
	)
	return err
}
