// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: read_models.sql

package sqlitequery

import (
	"context"
	"database/sql"
	"strings"
)

const deliveryBacklog = `-- name: DeliveryBacklog :one
SELECT COUNT(*) AS pending,CAST(COALESCE(MIN(due_at),0) AS INTEGER) AS oldest_due_at FROM deliveries WHERE state='pending'
`

type DeliveryBacklogRow struct {
	Pending     int64 `json:"pending"`
	OldestDueAt int64 `json:"oldest_due_at"`
}

func (q *Queries) DeliveryBacklog(ctx context.Context) (DeliveryBacklogRow, error) {
	row := q.db.QueryRowContext(ctx, deliveryBacklog)
	var i DeliveryBacklogRow
	err := row.Scan(&i.Pending, &i.OldestDueAt)
	return i, err
}

const listMonitorSnapshots = `-- name: ListMonitorSnapshots :many
SELECT m.id,m.config_version,m.generation,m.kind,m.enabled,m.interval_ms,m.config_json,
       r.monitor_id AS runtime_monitor_id,r.config_version AS runtime_config_version,r.generation AS runtime_generation,
       r.state,r.failures,r.successes,r.last_round_id,r.last_collected_at,r.heartbeat_version,r.heartbeat_at,
       d.payload AS engine_json
FROM monitors m
LEFT JOIN monitor_runtime r ON r.monitor_id=m.id
LEFT JOIN documents d ON d.kind='engineMonitor' AND d.id=m.id
ORDER BY m.id
`

type ListMonitorSnapshotsRow struct {
	ID                   string         `json:"id"`
	ConfigVersion        int64          `json:"config_version"`
	Generation           int64          `json:"generation"`
	Kind                 string         `json:"kind"`
	Enabled              int64          `json:"enabled"`
	IntervalMs           int64          `json:"interval_ms"`
	ConfigJson           string         `json:"config_json"`
	RuntimeMonitorID     sql.NullString `json:"runtime_monitor_id"`
	RuntimeConfigVersion sql.NullInt64  `json:"runtime_config_version"`
	RuntimeGeneration    sql.NullInt64  `json:"runtime_generation"`
	State                sql.NullString `json:"state"`
	Failures             sql.NullInt64  `json:"failures"`
	Successes            sql.NullInt64  `json:"successes"`
	LastRoundID          sql.NullString `json:"last_round_id"`
	LastCollectedAt      sql.NullInt64  `json:"last_collected_at"`
	HeartbeatVersion     sql.NullInt64  `json:"heartbeat_version"`
	HeartbeatAt          sql.NullInt64  `json:"heartbeat_at"`
	EngineJson           sql.NullString `json:"engine_json"`
}

func (q *Queries) ListMonitorSnapshots(ctx context.Context) ([]ListMonitorSnapshotsRow, error) {
	rows, err := q.db.QueryContext(ctx, listMonitorSnapshots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMonitorSnapshotsRow{}
	for rows.Next() {
		var i ListMonitorSnapshotsRow
		if err := rows.Scan(
			&i.ID,
			&i.ConfigVersion,
			&i.Generation,
			&i.Kind,
			&i.Enabled,
			&i.IntervalMs,
			&i.ConfigJson,
			&i.RuntimeMonitorID,
			&i.RuntimeConfigVersion,
			&i.RuntimeGeneration,
			&i.State,
			&i.Failures,
			&i.Successes,
			&i.LastRoundID,
			&i.LastCollectedAt,
			&i.HeartbeatVersion,
			&i.HeartbeatAt,
			&i.EngineJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readLatencyAggregates = `-- name: ReadLatencyAggregates :many
SELECT monitor_id, bucket_at, width_ms, up_ms, down_ms, unknown_ms, excluded_ms, latency_total_ms, round_count, successful_round_count FROM aggregates
WHERE bucket_at>=?1 AND bucket_at<?2 AND width_ms=?3 AND monitor_id IN (/*SLICE:ids*/?)
ORDER BY monitor_id,bucket_at
`

type ReadLatencyAggregatesParams struct {
	FromMs  int64    `json:"from_ms"`
	ToMs    int64    `json:"to_ms"`
	WidthMs int64    `json:"width_ms"`
	Ids     []string `json:"ids"`
}

func (q *Queries) ReadLatencyAggregates(ctx context.Context, arg ReadLatencyAggregatesParams) ([]Aggregate, error) {
	query := readLatencyAggregates
	var queryParams []interface{}
	queryParams = append(queryParams, arg.FromMs)
	queryParams = append(queryParams, arg.ToMs)
	queryParams = append(queryParams, arg.WidthMs)
	if len(arg.Ids) > 0 {
		for _, v := range arg.Ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(arg.Ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Aggregate{}
	for rows.Next() {
		var i Aggregate
		if err := rows.Scan(
			&i.MonitorID,
			&i.BucketAt,
			&i.WidthMs,
			&i.UpMs,
			&i.DownMs,
			&i.UnknownMs,
			&i.ExcludedMs,
			&i.LatencyTotalMs,
			&i.RoundCount,
			&i.SuccessfulRoundCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readMonitorSnapshots = `-- name: ReadMonitorSnapshots :many
SELECT m.id,m.config_version,m.generation,m.kind,m.enabled,m.interval_ms,m.config_json,
       r.monitor_id AS runtime_monitor_id,r.config_version AS runtime_config_version,r.generation AS runtime_generation,
       r.state,r.failures,r.successes,r.last_round_id,r.last_collected_at,r.heartbeat_version,r.heartbeat_at,
       d.payload AS engine_json
FROM monitors m
LEFT JOIN monitor_runtime r ON r.monitor_id=m.id
LEFT JOIN documents d ON d.kind='engineMonitor' AND d.id=m.id
WHERE m.id IN (/*SLICE:ids*/?)
ORDER BY m.id
`

type ReadMonitorSnapshotsRow struct {
	ID                   string         `json:"id"`
	ConfigVersion        int64          `json:"config_version"`
	Generation           int64          `json:"generation"`
	Kind                 string         `json:"kind"`
	Enabled              int64          `json:"enabled"`
	IntervalMs           int64          `json:"interval_ms"`
	ConfigJson           string         `json:"config_json"`
	RuntimeMonitorID     sql.NullString `json:"runtime_monitor_id"`
	RuntimeConfigVersion sql.NullInt64  `json:"runtime_config_version"`
	RuntimeGeneration    sql.NullInt64  `json:"runtime_generation"`
	State                sql.NullString `json:"state"`
	Failures             sql.NullInt64  `json:"failures"`
	Successes            sql.NullInt64  `json:"successes"`
	LastRoundID          sql.NullString `json:"last_round_id"`
	LastCollectedAt      sql.NullInt64  `json:"last_collected_at"`
	HeartbeatVersion     sql.NullInt64  `json:"heartbeat_version"`
	HeartbeatAt          sql.NullInt64  `json:"heartbeat_at"`
	EngineJson           sql.NullString `json:"engine_json"`
}

func (q *Queries) ReadMonitorSnapshots(ctx context.Context, ids []string) ([]ReadMonitorSnapshotsRow, error) {
	query := readMonitorSnapshots
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReadMonitorSnapshotsRow{}
	for rows.Next() {
		var i ReadMonitorSnapshotsRow
		if err := rows.Scan(
			&i.ID,
			&i.ConfigVersion,
			&i.Generation,
			&i.Kind,
			&i.Enabled,
			&i.IntervalMs,
			&i.ConfigJson,
			&i.RuntimeMonitorID,
			&i.RuntimeConfigVersion,
			&i.RuntimeGeneration,
			&i.State,
			&i.Failures,
			&i.Successes,
			&i.LastRoundID,
			&i.LastCollectedAt,
			&i.HeartbeatVersion,
			&i.HeartbeatAt,
			&i.EngineJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readMonitors = `-- name: ReadMonitors :many
SELECT id, config_version, generation, kind, enabled, interval_ms, config_json FROM monitors WHERE id IN (/*SLICE:ids*/?) ORDER BY id
`

func (q *Queries) ReadMonitors(ctx context.Context, ids []string) ([]Monitor, error) {
	query := readMonitors
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Monitor{}
	for rows.Next() {
		var i Monitor
		if err := rows.Scan(
			&i.ID,
			&i.ConfigVersion,
			&i.Generation,
			&i.Kind,
			&i.Enabled,
			&i.IntervalMs,
			&i.ConfigJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readRoundBuckets = `-- name: ReadRoundBuckets :many
SELECT monitor_id,
       CAST((finished_at / CAST(?1 AS INTEGER)) * CAST(?1 AS INTEGER) AS INTEGER) AS bucket_at,
       CAST(SUM(latency_ms) AS INTEGER) AS latency_total_ms,
       COUNT(*) AS round_count,
       CAST(SUM(CASE WHEN success=1 THEN 1 ELSE 0 END) AS INTEGER) AS successful_round_count
FROM rounds
WHERE finished_at>=?2 AND finished_at<?3 AND monitor_id IN (/*SLICE:ids*/?)
GROUP BY monitor_id,bucket_at
ORDER BY monitor_id,bucket_at
`

type ReadRoundBucketsParams struct {
	WidthMs int64    `json:"width_ms"`
	FromMs  int64    `json:"from_ms"`
	ToMs    int64    `json:"to_ms"`
	Ids     []string `json:"ids"`
}

type ReadRoundBucketsRow struct {
	MonitorID            string `json:"monitor_id"`
	BucketAt             int64  `json:"bucket_at"`
	LatencyTotalMs       int64  `json:"latency_total_ms"`
	RoundCount           int64  `json:"round_count"`
	SuccessfulRoundCount int64  `json:"successful_round_count"`
}

func (q *Queries) ReadRoundBuckets(ctx context.Context, arg ReadRoundBucketsParams) ([]ReadRoundBucketsRow, error) {
	query := readRoundBuckets
	var queryParams []interface{}
	queryParams = append(queryParams, arg.WidthMs)
	queryParams = append(queryParams, arg.FromMs)
	queryParams = append(queryParams, arg.ToMs)
	if len(arg.Ids) > 0 {
		for _, v := range arg.Ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(arg.Ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReadRoundBucketsRow{}
	for rows.Next() {
		var i ReadRoundBucketsRow
		if err := rows.Scan(
			&i.MonitorID,
			&i.BucketAt,
			&i.LatencyTotalMs,
			&i.RoundCount,
			&i.SuccessfulRoundCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readStatisticsIntervals = `-- name: ReadStatisticsIntervals :many
SELECT id,monitor_id,state,started_at,ended_at FROM state_intervals
WHERE started_at<?1 AND (ended_at IS NULL OR ended_at>?2) AND monitor_id IN (/*SLICE:ids*/?)
ORDER BY monitor_id,started_at,id
`

type ReadStatisticsIntervalsParams struct {
	ToMs   int64         `json:"to_ms"`
	FromMs sql.NullInt64 `json:"from_ms"`
	Ids    []string      `json:"ids"`
}

func (q *Queries) ReadStatisticsIntervals(ctx context.Context, arg ReadStatisticsIntervalsParams) ([]StateInterval, error) {
	query := readStatisticsIntervals
	var queryParams []interface{}
	queryParams = append(queryParams, arg.ToMs)
	queryParams = append(queryParams, arg.FromMs)
	if len(arg.Ids) > 0 {
		for _, v := range arg.Ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(arg.Ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StateInterval{}
	for rows.Next() {
		var i StateInterval
		if err := rows.Scan(
			&i.ID,
			&i.MonitorID,
			&i.State,
			&i.StartedAt,
			&i.EndedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
