// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgresquery

import (
	"database/sql"
)

type Aggregate struct {
	MonitorID            string `json:"monitor_id"`
	BucketAt             int64  `json:"bucket_at"`
	WidthMs              int64  `json:"width_ms"`
	UpMs                 int64  `json:"up_ms"`
	DownMs               int64  `json:"down_ms"`
	UnknownMs            int64  `json:"unknown_ms"`
	ExcludedMs           int64  `json:"excluded_ms"`
	LatencyTotalMs       int64  `json:"latency_total_ms"`
	RoundCount           int64  `json:"round_count"`
	SuccessfulRoundCount int64  `json:"successful_round_count"`
}

type Attempt struct {
	RoundID    string `json:"round_id"`
	Number     int64  `json:"number"`
	StartedAt  int64  `json:"started_at"`
	FinishedAt int64  `json:"finished_at"`
	Success    int64  `json:"success"`
	LatencyMs  int64  `json:"latency_ms"`
	Error      string `json:"error"`
	Detail     string `json:"detail"`
}

type Delivery struct {
	ID         string `json:"id"`
	EventID    string `json:"event_id"`
	ChannelID  string `json:"channel_id"`
	Generation int64  `json:"generation"`
	State      string `json:"state"`
	DueAt      int64  `json:"due_at"`
	Attempts   int64  `json:"attempts"`
	LeaseToken string `json:"lease_token"`
	LeaseUntil int64  `json:"lease_until"`
	LastError  string `json:"last_error"`
	Payload    string `json:"payload"`
}

type Document struct {
	Kind    string `json:"kind"`
	ID      string `json:"id"`
	Payload string `json:"payload"`
}

type Event struct {
	ID         string `json:"id"`
	MonitorID  string `json:"monitor_id"`
	Generation int64  `json:"generation"`
	Kind       string `json:"kind"`
	CreatedAt  int64  `json:"created_at"`
	Payload    string `json:"payload"`
}

type Monitor struct {
	ID            string `json:"id"`
	ConfigVersion int64  `json:"config_version"`
	Generation    int64  `json:"generation"`
	Kind          string `json:"kind"`
	Enabled       int64  `json:"enabled"`
	IntervalMs    int64  `json:"interval_ms"`
	ConfigJson    string `json:"config_json"`
}

type MonitorRuntime struct {
	MonitorID        string `json:"monitor_id"`
	ConfigVersion    int64  `json:"config_version"`
	Generation       int64  `json:"generation"`
	State            string `json:"state"`
	Failures         int64  `json:"failures"`
	Successes        int64  `json:"successes"`
	LastRoundID      string `json:"last_round_id"`
	LastCollectedAt  int64  `json:"last_collected_at"`
	HeartbeatVersion int64  `json:"heartbeat_version"`
	HeartbeatAt      int64  `json:"heartbeat_at"`
}

type PageDomain struct {
	Domain string `json:"domain"`
	PageID string `json:"page_id"`
}

type PageSlug struct {
	PageID string `json:"page_id"`
	Slug   string `json:"slug"`
}

type Round struct {
	ID            string `json:"id"`
	MonitorID     string `json:"monitor_id"`
	ConfigVersion int64  `json:"config_version"`
	Generation    int64  `json:"generation"`
	StartedAt     int64  `json:"started_at"`
	FinishedAt    int64  `json:"finished_at"`
	Success       int64  `json:"success"`
	LatencyMs     int64  `json:"latency_ms"`
}

type StateInterval struct {
	ID        string        `json:"id"`
	MonitorID string        `json:"monitor_id"`
	State     string        `json:"state"`
	StartedAt int64         `json:"started_at"`
	EndedAt   sql.NullInt64 `json:"ended_at"`
}

type Watermark struct {
	Name string `json:"name"`
	AtMs int64  `json:"at_ms"`
}
