export { default as TableOfContents } from './TableOfContents.vue'
export { default as TableOfContentsGroup } from './TableOfContentsGroup.vue'
export { default as TableOfContentsItem } from './TableOfContentsItem.vue'
export { default as TableOfContentsList } from './TableOfContentsList.vue'
export { default as TableOfContentsTitle } from './TableOfContentsTitle.vue'
export { useTableOfContentsActiveId } from './use-table-of-contents-active-id'
export type { UseTableOfContentsActiveIdOptions } from './use-table-of-contents-active-id'
