// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type Ack = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    ok: boolean;
};

export type AssetUrl = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    url: string;
};

export type AssetWrite = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    base64: string;
    contentType: string;
    filename: string;
};

export type Attempt = {
    detail?: unknown;
    error?: string;
    finishedAt: number;
    latencyMs: number;
    number: number;
    startedAt: number;
    success: boolean;
};

export type Audit = {
    action: string;
    readonly createdAt: number;
    readonly id: string;
    resourceId: string;
    resourceType: string;
    userId: string;
    username: string;
};

export type Availability = {
    coverage: number | null;
    downMs: number;
    effectiveMs: number;
    excludedMs: number;
    from: number;
    to: number;
    unknownMs: number;
    upMs: number;
    uptime: number | null;
};

export type BeszelConfig = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    email: string;
    enabled: boolean;
    passwordSecretId: string;
    pollSeconds: number;
    url: string;
};

export type CertificateConfig = {
    connection?: ConnectionConfig;
    readonly daysRemaining: number;
    readonly expiresAt: number;
    readonly fingerprint: string;
    host: string;
    notifyRenewal?: boolean;
    port: number;
    readonly state: string;
    tls?: TlsConfig;
    warningDays?: Array<number>;
};

export type Channel = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    readonly createdAt: number;
    enabled: boolean;
    readonly id: string;
    name: string;
    serviceUrlSecretId: string;
    readonly updatedAt: number;
};

export type ConnectionConfig = {
    dnsServer: string;
    fixedIp: string;
    proxyPasswordSecretRef?: string;
    proxyUrl: string;
    proxyUsername?: string;
};

export type Container = {
    cpu: number;
    id: string;
    image: string;
    memory: number;
    name: string;
    status: string;
    updatedAt: number;
};

export type ContainersResponse = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    error?: string;
    items: Array<Container>;
    source: string;
    stale: boolean;
    syncedAt: number;
};

export type Credentials = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    password: string;
    username: string;
};

export type DnsConfig = {
    expectedRCode?: string;
    expectedValues?: Array<string>;
    matchMode: string;
    name: string;
    protocol?: string;
    recordType: string;
    server?: string;
};

export type DeliveryView = {
    attempts: number;
    channelId: string;
    createdAt: number;
    dueAt: number;
    eventId: string;
    id: string;
    kind: string;
    lastError: string;
    monitorId: string;
    status: string;
};

export type ErrorDetail = {
    /**
     * Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
     */
    location?: string;
    /**
     * Error message text
     */
    message?: string;
    /**
     * The value at the given location
     */
    value?: unknown;
};

export type ErrorModel = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    detail?: string;
    /**
     * Optional list of individual error details
     */
    errors?: Array<ErrorDetail>;
    /**
     * A URI reference that identifies the specific occurrence of the problem.
     */
    instance?: string;
    /**
     * HTTP status code
     */
    status?: number;
    /**
     * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
     */
    title?: string;
    /**
     * A URI reference to human-readable documentation for the error.
     */
    type?: string;
};

export type HttpAssertions = {
    headers?: Array<ValueAssertion>;
    json?: Array<JsonAssertion>;
    maxLatencyMs?: number;
    regex?: Array<string>;
    statusCodes?: Array<number>;
    statusRanges?: Array<StatusRange>;
    textContains?: Array<string>;
    textNotContains?: Array<string>;
};

export type HttpAuth = {
    header?: string;
    prefix?: string;
    secretRef?: string;
    type: string;
    username?: string;
    usernameSecretRef?: string;
};

export type HttpBody = {
    base64?: string;
    charset?: string;
    contentType?: string;
    fields?: Array<NameValue>;
    files?: Array<MultipartFile>;
    format: string;
    secretRef?: string;
    text?: string;
};

export type HttpConfig = {
    acceptEncoding?: string;
    assertions?: HttpAssertions;
    auth?: HttpAuth;
    body?: HttpBody;
    connection?: ConnectionConfig;
    headers?: Array<NameValue>;
    host?: string;
    maxResponseBytes?: number;
    method?: string;
    query?: Array<NameValue>;
    redirects?: RedirectConfig;
    requestGzip?: boolean;
    responseCharset?: string;
    tls?: TlsConfig;
    url: string;
};

export type HeartbeatConfig = {
    readonly description: string;
    graceSeconds?: number;
    readonly lastReceivedAt: number;
    readonly lastSuccess: boolean;
    periodSeconds?: number;
};

export type HeartbeatReport = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    description?: string;
    status?: 'up' | 'down';
};

export type HeartbeatToken = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    token: string;
    url: string;
};

export type HistoryPoint = {
    at: number;
    cpu: number;
    disk: number;
    memory: number;
    networkIn: number;
    networkOut: number;
};

export type HistoryResponse = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    error?: string;
    intervalMs: number;
    items: Array<HistoryPoint>;
    range: string;
    source: string;
    stale: boolean;
    syncedAt: number;
};

export type Incident = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    body: string;
    readonly createdAt: number;
    readonly id: string;
    impact: 'none' | 'partial' | 'outage';
    monitorIds: Array<string>;
    pageIds: Array<string>;
    readonly resolvedAt: number;
    status: 'investigating' | 'identified' | 'monitoring' | 'resolved';
    title: string;
    readonly updatedAt: number;
    readonly updates: Array<IncidentUpdate>;
};

export type IncidentProgress = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    body: string;
    status: 'investigating' | 'identified' | 'monitoring' | 'resolved';
};

export type IncidentUpdate = {
    body: string;
    readonly createdAt: number;
    readonly id: string;
    status: 'investigating' | 'identified' | 'monitoring' | 'resolved';
};

export type ItemsAudit = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    items: Array<Audit>;
};

export type ItemsChannel = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    items: Array<Channel>;
};

export type ItemsDeliveryView = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    items: Array<DeliveryView>;
};

export type ItemsIncident = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    items: Array<Incident>;
};

export type ItemsMaintenance = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    items: Array<Maintenance>;
};

export type ItemsMonitor = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    items: Array<Monitor>;
};

export type ItemsPage = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    items: Array<Page>;
};

export type ItemsSecret = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    items: Array<Secret>;
};

export type ItemsUser = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    items: Array<User>;
};

export type JsonAssertion = {
    operator: string;
    pointer: string;
    value?: unknown;
};

export type LatencyPoint = {
    at: number;
    latencyMs: number;
    success: boolean;
};

export type Link = {
    label: string;
    url: string;
};

export type Maintenance = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    readonly createdAt: number;
    description: string;
    endsAt: number;
    readonly id: string;
    monitorIds: Array<string>;
    name: string;
    pageIds: Array<string>;
    startsAt: number;
    timezone: string;
    readonly updatedAt: number;
};

export type Monitor = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    certificate?: CertificateConfig;
    readonly configVersion: number;
    readonly createdAt: number;
    description?: string;
    dns?: DnsConfig;
    enabled?: boolean;
    readonly failureCount: number;
    failureThreshold?: number;
    group?: string;
    heartbeat?: HeartbeatConfig;
    http?: HttpConfig;
    readonly id: string;
    intervalSeconds?: number;
    readonly lastCheckedAt: number;
    name: string;
    readonly nextCheckAt: number;
    notificationChannelIds?: Array<string>;
    notifyRecovery?: boolean;
    recoveryThreshold?: number;
    reminderSeconds?: number;
    retries?: number;
    retryDelaySeconds?: number;
    readonly state: string;
    readonly successCount: number;
    tags?: Array<string>;
    tcp?: TcpConfig;
    timeoutSeconds?: number;
    type: string;
    readonly updatedAt: number;
};

export type MonitorHistory = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    availability: Availability;
    latency: Array<LatencyPoint>;
    rounds: Array<Round>;
};

export type MonitorWrite = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    certificate?: CertificateConfig;
    readonly configVersion: number;
    readonly createdAt: number;
    description?: string;
    dns?: DnsConfig;
    enabled?: boolean;
    readonly failureCount: number;
    failureThreshold?: number;
    group?: string;
    heartbeat?: HeartbeatConfig;
    http?: HttpConfig;
    readonly id: string;
    intervalSeconds?: number;
    readonly lastCheckedAt: number;
    name: string;
    readonly nextCheckAt: number;
    notificationChannelIds?: Array<string>;
    notifyRecovery?: boolean;
    recoveryThreshold?: number;
    reminderSeconds?: number;
    retries?: number;
    retryDelaySeconds?: number;
    readonly state: string;
    readonly successCount: number;
    tags?: Array<string>;
    tcp?: TcpConfig;
    timeoutSeconds?: number;
    type: string;
    readonly updatedAt: number;
};

export type MultipartFile = {
    base64?: string;
    contentType?: string;
    field: string;
    filename: string;
    secretRef?: string;
};

export type NameValue = {
    name: string;
    secretRef?: string;
    value?: string;
};

export type Page = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    readonly createdAt: number;
    domain: string;
    draft: PageConfig;
    readonly id: string;
    name: string;
    readonly published?: PageConfig;
    readonly publishedAt: number;
    readonly publishedDomain?: string;
    readonly publishedSlug?: string;
    slug: string;
    readonly updatedAt: number;
    readonly version: number;
};

export type PageConfig = {
    brandColor: string;
    colorScheme: 'system' | 'light' | 'dark';
    description: string;
    groups: Array<PageGroup>;
    links: Array<Link>;
    logoUrl: string;
    title: string;
};

export type PageGroup = {
    id: string;
    monitors: Array<PageMonitor>;
    name: string;
};

export type PageMonitor = {
    alias: string;
    monitorId: string;
    showLatency: boolean;
    showUptime: boolean;
};

export type ProfileWrite = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    locale: 'zh-CN' | 'en';
    name: string;
    oldPassword?: string;
    password?: string;
    timezone: string;
};

export type PublicCertificate = {
    daysRemaining: number;
    expiresAt: number;
    state: string;
};

export type PublicGroup = {
    readonly id: string;
    monitors: Array<PublicMonitor>;
    name: string;
};

export type PublicIncident = {
    body: string;
    readonly createdAt: number;
    readonly id: string;
    impact: string;
    resolvedAt: number;
    status: string;
    title: string;
    updates: Array<IncidentUpdate>;
};

export type PublicMaintenance = {
    description: string;
    endsAt: number;
    readonly id: string;
    name: string;
    startsAt: number;
};

export type PublicMonitor = {
    availability: Availability;
    certificate?: PublicCertificate;
    readonly id: string;
    latency: Array<LatencyPoint>;
    maintenance: boolean;
    name: string;
    paused: boolean;
    state: string;
    type: string;
};

export type PublicPage = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    config: PageConfig;
    groups: Array<PublicGroup>;
    readonly id: string;
    incidents: Array<PublicIncident>;
    maintenance: Array<PublicMaintenance>;
    slug: string;
    state: string;
    readonly updatedAt: number;
};

export type RedirectConfig = {
    enabled?: boolean;
    maxHops?: number;
    scope: string;
};

export type Retention = {
    attemptDays: number;
    fiveMinuteDays: number;
    historyMonths: number;
    roundDays: number;
};

export type Round = {
    attempts: Array<Attempt>;
    configVersion: number;
    finishedAt: number;
    generation: number;
    id: string;
    latencyMs: number;
    monitorId: string;
    startedAt: number;
    success: boolean;
};

export type Secret = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    readonly createdAt: number;
    readonly id: string;
    name: string;
    readonly updatedAt: number;
};

export type SecretWrite = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    name: string;
    value: string;
};

export type Settings = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    allowedDomains: Array<string>;
    locale: 'zh-CN' | 'en';
    organizationName: string;
    retention: Retention;
    timezone: string;
};

export type SetupBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    organizationName: string;
    password: string;
    timezone: string;
    username: string;
};

export type SetupStatus = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    required: boolean;
};

export type StatusRange = {
    max?: number;
    min?: number;
};

export type System = {
    cpu: number;
    disk: number;
    host: string;
    id: string;
    info: SystemInfo;
    memory: number;
    name: string;
    networkIn?: number;
    networkOut?: number;
    stale: boolean;
    status: string;
    updatedAt: number;
};

export type SystemInfo = {
    agentVersion: string;
    cores: number;
    cpuModel: string;
    hostname: string;
    kernel: string;
    threads: number;
    uptimeSeconds: number;
};

export type SystemsResponse = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    error?: string;
    items: Array<System>;
    source: string;
    stale: boolean;
    syncedAt: number;
    version: string;
};

export type TcpConfig = {
    charset?: string;
    connection?: ConnectionConfig;
    host: string;
    maxReceiveBytes?: number;
    port: number;
    receiveContains?: string;
    receiveRegex?: string;
    sendBase64?: string;
    sendSecretRef?: string;
    sendText?: string;
    tls?: TlsConfig;
};

export type TlsConfig = {
    caSecretRef?: string;
    clientCertificateSecretRef?: string;
    clientKeySecretRef?: string;
    enabled?: boolean;
    insecureSkipVerify?: boolean;
    maxVersion?: string;
    minVersion: string;
    serverName?: string;
};

export type User = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    readonly createdAt: number;
    enabled: boolean;
    readonly id: string;
    locale: 'zh-CN' | 'en';
    name: string;
    role: 'admin' | 'operator' | 'viewer';
    timezone: string;
    readonly updatedAt: number;
    username: string;
};

export type UserWrite = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    enabled: boolean | null;
    locale: 'zh-CN' | 'en';
    name: string;
    password?: string;
    role: 'admin' | 'operator' | 'viewer';
    timezone: string;
    username: string;
};

export type ValueAssertion = {
    name: string;
    operator: string;
    value?: string;
};

export type AckWritable = {
    ok: boolean;
};

export type AssetUrlWritable = {
    url: string;
};

export type AssetWriteWritable = {
    base64: string;
    contentType: string;
    filename: string;
};

export type AuditWritable = {
    action: string;
    resourceId: string;
    resourceType: string;
    userId: string;
    username: string;
};

export type BeszelConfigWritable = {
    email: string;
    enabled: boolean;
    passwordSecretId: string;
    pollSeconds: number;
    url: string;
};

export type CertificateConfigWritable = {
    connection?: ConnectionConfig;
    host: string;
    notifyRenewal?: boolean;
    port: number;
    tls?: TlsConfig;
    warningDays?: Array<number>;
};

export type ChannelWritable = {
    enabled: boolean;
    name: string;
    serviceUrlSecretId: string;
};

export type ContainersResponseWritable = {
    error?: string;
    items: Array<Container>;
    source: string;
    stale: boolean;
    syncedAt: number;
};

export type CredentialsWritable = {
    password: string;
    username: string;
};

export type ErrorModelWritable = {
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    detail?: string;
    /**
     * Optional list of individual error details
     */
    errors?: Array<ErrorDetail>;
    /**
     * A URI reference that identifies the specific occurrence of the problem.
     */
    instance?: string;
    /**
     * HTTP status code
     */
    status?: number;
    /**
     * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
     */
    title?: string;
    /**
     * A URI reference to human-readable documentation for the error.
     */
    type?: string;
};

export type HeartbeatConfigWritable = {
    graceSeconds?: number;
    periodSeconds?: number;
};

export type HeartbeatReportWritable = {
    description?: string;
    status?: 'up' | 'down';
};

export type HeartbeatTokenWritable = {
    token: string;
    url: string;
};

export type HistoryResponseWritable = {
    error?: string;
    intervalMs: number;
    items: Array<HistoryPoint>;
    range: string;
    source: string;
    stale: boolean;
    syncedAt: number;
};

export type IncidentWritable = {
    body: string;
    impact: 'none' | 'partial' | 'outage';
    monitorIds: Array<string>;
    pageIds: Array<string>;
    status: 'investigating' | 'identified' | 'monitoring' | 'resolved';
    title: string;
};

export type IncidentProgressWritable = {
    body: string;
    status: 'investigating' | 'identified' | 'monitoring' | 'resolved';
};

export type IncidentUpdateWritable = {
    body: string;
    status: 'investigating' | 'identified' | 'monitoring' | 'resolved';
};

export type ItemsAuditWritable = {
    items: Array<AuditWritable>;
};

export type ItemsChannelWritable = {
    items: Array<ChannelWritable>;
};

export type ItemsDeliveryViewWritable = {
    items: Array<DeliveryView>;
};

export type ItemsIncidentWritable = {
    items: Array<IncidentWritable>;
};

export type ItemsMaintenanceWritable = {
    items: Array<MaintenanceWritable>;
};

export type ItemsMonitorWritable = {
    items: Array<MonitorWritable>;
};

export type ItemsPageWritable = {
    items: Array<PageWritable>;
};

export type ItemsSecretWritable = {
    items: Array<SecretWritable>;
};

export type ItemsUserWritable = {
    items: Array<UserWritable>;
};

export type MaintenanceWritable = {
    description: string;
    endsAt: number;
    monitorIds: Array<string>;
    name: string;
    pageIds: Array<string>;
    startsAt: number;
    timezone: string;
};

export type MonitorWritable = {
    certificate?: CertificateConfigWritable;
    description?: string;
    dns?: DnsConfig;
    enabled?: boolean;
    failureThreshold?: number;
    group?: string;
    heartbeat?: HeartbeatConfigWritable;
    http?: HttpConfig;
    intervalSeconds?: number;
    name: string;
    notificationChannelIds?: Array<string>;
    notifyRecovery?: boolean;
    recoveryThreshold?: number;
    reminderSeconds?: number;
    retries?: number;
    retryDelaySeconds?: number;
    tags?: Array<string>;
    tcp?: TcpConfig;
    timeoutSeconds?: number;
    type: string;
};

export type MonitorHistoryWritable = {
    availability: Availability;
    latency: Array<LatencyPoint>;
    rounds: Array<Round>;
};

export type MonitorWriteWritable = {
    certificate?: CertificateConfigWritable;
    description?: string;
    dns?: DnsConfig;
    enabled?: boolean;
    failureThreshold?: number;
    group?: string;
    heartbeat?: HeartbeatConfigWritable;
    http?: HttpConfig;
    intervalSeconds?: number;
    name: string;
    notificationChannelIds?: Array<string>;
    notifyRecovery?: boolean;
    recoveryThreshold?: number;
    reminderSeconds?: number;
    retries?: number;
    retryDelaySeconds?: number;
    tags?: Array<string>;
    tcp?: TcpConfig;
    timeoutSeconds?: number;
    type: string;
};

export type PageWritable = {
    domain: string;
    draft: PageConfig;
    name: string;
    slug: string;
};

export type ProfileWriteWritable = {
    locale: 'zh-CN' | 'en';
    name: string;
    oldPassword?: string;
    password?: string;
    timezone: string;
};

export type PublicGroupWritable = {
    monitors: Array<PublicMonitorWritable>;
    name: string;
};

export type PublicIncidentWritable = {
    body: string;
    impact: string;
    resolvedAt: number;
    status: string;
    title: string;
    updates: Array<IncidentUpdateWritable>;
};

export type PublicMaintenanceWritable = {
    description: string;
    endsAt: number;
    name: string;
    startsAt: number;
};

export type PublicMonitorWritable = {
    availability: Availability;
    certificate?: PublicCertificate;
    latency: Array<LatencyPoint>;
    maintenance: boolean;
    name: string;
    paused: boolean;
    state: string;
    type: string;
};

export type PublicPageWritable = {
    config: PageConfig;
    groups: Array<PublicGroupWritable>;
    incidents: Array<PublicIncidentWritable>;
    maintenance: Array<PublicMaintenanceWritable>;
    slug: string;
    state: string;
};

export type SecretWritable = {
    name: string;
};

export type SecretWriteWritable = {
    name: string;
    value: string;
};

export type SettingsWritable = {
    allowedDomains: Array<string>;
    locale: 'zh-CN' | 'en';
    organizationName: string;
    retention: Retention;
    timezone: string;
};

export type SetupBodyWritable = {
    organizationName: string;
    password: string;
    timezone: string;
    username: string;
};

export type SetupStatusWritable = {
    required: boolean;
};

export type SystemsResponseWritable = {
    error?: string;
    items: Array<System>;
    source: string;
    stale: boolean;
    syncedAt: number;
    version: string;
};

export type UserWritable = {
    enabled: boolean;
    locale: 'zh-CN' | 'en';
    name: string;
    role: 'admin' | 'operator' | 'viewer';
    timezone: string;
    username: string;
};

export type UserWriteWritable = {
    enabled: boolean | null;
    locale: 'zh-CN' | 'en';
    name: string;
    password?: string;
    role: 'admin' | 'operator' | 'viewer';
    timezone: string;
    username: string;
};

export type ReportHeartbeatData = {
    body: HeartbeatReportWritable;
    path: {
        id: string;
        token: string;
    };
    query?: never;
    url: '/api/heartbeat/{id}/{token}';
};

export type ReportHeartbeatErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ReportHeartbeatError = ReportHeartbeatErrors[keyof ReportHeartbeatErrors];

export type ReportHeartbeatResponses = {
    /**
     * OK
     */
    200: Ack;
};

export type ReportHeartbeatResponse = ReportHeartbeatResponses[keyof ReportHeartbeatResponses];

export type GetPublicPageData = {
    body?: never;
    path: {
        slug: string;
    };
    query?: never;
    url: '/api/public/pages/{slug}';
};

export type GetPublicPageErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetPublicPageError = GetPublicPageErrors[keyof GetPublicPageErrors];

export type GetPublicPageResponses = {
    /**
     * OK
     */
    200: PublicPage;
};

export type GetPublicPageResponse = GetPublicPageResponses[keyof GetPublicPageResponses];

export type ResolvePublicPageData = {
    body?: never;
    path?: never;
    query?: {
        host?: string;
    };
    url: '/api/public/resolve';
};

export type ResolvePublicPageErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ResolvePublicPageError = ResolvePublicPageErrors[keyof ResolvePublicPageErrors];

export type ResolvePublicPageResponses = {
    /**
     * OK
     */
    200: PublicPage;
};

export type ResolvePublicPageResponse = ResolvePublicPageResponses[keyof ResolvePublicPageResponses];

export type UploadAssetData = {
    body: AssetWriteWritable;
    path?: never;
    query?: never;
    url: '/api/v1/assets';
};

export type UploadAssetErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type UploadAssetError = UploadAssetErrors[keyof UploadAssetErrors];

export type UploadAssetResponses = {
    /**
     * OK
     */
    200: AssetUrl;
};

export type UploadAssetResponse = UploadAssetResponses[keyof UploadAssetResponses];

export type ListAuditData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/audit';
};

export type ListAuditErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ListAuditError = ListAuditErrors[keyof ListAuditErrors];

export type ListAuditResponses = {
    /**
     * OK
     */
    200: ItemsAudit;
};

export type ListAuditResponse = ListAuditResponses[keyof ListAuditResponses];

export type GetBeszelConfigData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/beszel/config';
};

export type GetBeszelConfigErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetBeszelConfigError = GetBeszelConfigErrors[keyof GetBeszelConfigErrors];

export type GetBeszelConfigResponses = {
    /**
     * OK
     */
    200: BeszelConfig;
};

export type GetBeszelConfigResponse = GetBeszelConfigResponses[keyof GetBeszelConfigResponses];

export type UpdateBeszelConfigData = {
    body: BeszelConfigWritable;
    path?: never;
    query?: never;
    url: '/api/v1/beszel/config';
};

export type UpdateBeszelConfigErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type UpdateBeszelConfigError = UpdateBeszelConfigErrors[keyof UpdateBeszelConfigErrors];

export type UpdateBeszelConfigResponses = {
    /**
     * OK
     */
    200: BeszelConfig;
};

export type UpdateBeszelConfigResponse = UpdateBeszelConfigResponses[keyof UpdateBeszelConfigResponses];

export type ListBeszelSystemsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/beszel/systems';
};

export type ListBeszelSystemsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ListBeszelSystemsError = ListBeszelSystemsErrors[keyof ListBeszelSystemsErrors];

export type ListBeszelSystemsResponses = {
    /**
     * OK
     */
    200: SystemsResponse;
};

export type ListBeszelSystemsResponse = ListBeszelSystemsResponses[keyof ListBeszelSystemsResponses];

export type ListBeszelContainersData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/beszel/systems/{id}/containers';
};

export type ListBeszelContainersErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ListBeszelContainersError = ListBeszelContainersErrors[keyof ListBeszelContainersErrors];

export type ListBeszelContainersResponses = {
    /**
     * OK
     */
    200: ContainersResponse;
};

export type ListBeszelContainersResponse = ListBeszelContainersResponses[keyof ListBeszelContainersResponses];

export type GetBeszelHistoryData = {
    body?: never;
    path: {
        id: string;
    };
    query?: {
        range?: '1h' | '12h' | '24h' | '1w' | '30d';
    };
    url: '/api/v1/beszel/systems/{id}/history';
};

export type GetBeszelHistoryErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetBeszelHistoryError = GetBeszelHistoryErrors[keyof GetBeszelHistoryErrors];

export type GetBeszelHistoryResponses = {
    /**
     * OK
     */
    200: HistoryResponse;
};

export type GetBeszelHistoryResponse = GetBeszelHistoryResponses[keyof GetBeszelHistoryResponses];

export type ListChannelsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/channels';
};

export type ListChannelsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ListChannelsError = ListChannelsErrors[keyof ListChannelsErrors];

export type ListChannelsResponses = {
    /**
     * OK
     */
    200: ItemsChannel;
};

export type ListChannelsResponse = ListChannelsResponses[keyof ListChannelsResponses];

export type CreateChannelsData = {
    body: ChannelWritable;
    path?: never;
    query?: never;
    url: '/api/v1/channels';
};

export type CreateChannelsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type CreateChannelsError = CreateChannelsErrors[keyof CreateChannelsErrors];

export type CreateChannelsResponses = {
    /**
     * OK
     */
    200: Channel;
};

export type CreateChannelsResponse = CreateChannelsResponses[keyof CreateChannelsResponses];

export type DeleteChannelsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/channels/{id}';
};

export type DeleteChannelsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type DeleteChannelsError = DeleteChannelsErrors[keyof DeleteChannelsErrors];

export type DeleteChannelsResponses = {
    /**
     * OK
     */
    200: Ack;
};

export type DeleteChannelsResponse = DeleteChannelsResponses[keyof DeleteChannelsResponses];

export type GetChannelsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/channels/{id}';
};

export type GetChannelsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetChannelsError = GetChannelsErrors[keyof GetChannelsErrors];

export type GetChannelsResponses = {
    /**
     * OK
     */
    200: Channel;
};

export type GetChannelsResponse = GetChannelsResponses[keyof GetChannelsResponses];

export type UpdateChannelsData = {
    body: ChannelWritable;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/channels/{id}';
};

export type UpdateChannelsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type UpdateChannelsError = UpdateChannelsErrors[keyof UpdateChannelsErrors];

export type UpdateChannelsResponses = {
    /**
     * OK
     */
    200: Channel;
};

export type UpdateChannelsResponse = UpdateChannelsResponses[keyof UpdateChannelsResponses];

export type TestChannelData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/channels/{id}/test';
};

export type TestChannelErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type TestChannelError = TestChannelErrors[keyof TestChannelErrors];

export type TestChannelResponses = {
    /**
     * OK
     */
    200: Ack;
};

export type TestChannelResponse = TestChannelResponses[keyof TestChannelResponses];

export type ListDeliveriesData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
    };
    url: '/api/v1/deliveries';
};

export type ListDeliveriesErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ListDeliveriesError = ListDeliveriesErrors[keyof ListDeliveriesErrors];

export type ListDeliveriesResponses = {
    /**
     * OK
     */
    200: ItemsDeliveryView;
};

export type ListDeliveriesResponse = ListDeliveriesResponses[keyof ListDeliveriesResponses];

export type ListIncidentsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/incidents';
};

export type ListIncidentsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ListIncidentsError = ListIncidentsErrors[keyof ListIncidentsErrors];

export type ListIncidentsResponses = {
    /**
     * OK
     */
    200: ItemsIncident;
};

export type ListIncidentsResponse = ListIncidentsResponses[keyof ListIncidentsResponses];

export type CreateIncidentsData = {
    body: IncidentWritable;
    path?: never;
    query?: never;
    url: '/api/v1/incidents';
};

export type CreateIncidentsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type CreateIncidentsError = CreateIncidentsErrors[keyof CreateIncidentsErrors];

export type CreateIncidentsResponses = {
    /**
     * OK
     */
    200: Incident;
};

export type CreateIncidentsResponse = CreateIncidentsResponses[keyof CreateIncidentsResponses];

export type DeleteIncidentsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/incidents/{id}';
};

export type DeleteIncidentsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type DeleteIncidentsError = DeleteIncidentsErrors[keyof DeleteIncidentsErrors];

export type DeleteIncidentsResponses = {
    /**
     * OK
     */
    200: Ack;
};

export type DeleteIncidentsResponse = DeleteIncidentsResponses[keyof DeleteIncidentsResponses];

export type GetIncidentsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/incidents/{id}';
};

export type GetIncidentsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetIncidentsError = GetIncidentsErrors[keyof GetIncidentsErrors];

export type GetIncidentsResponses = {
    /**
     * OK
     */
    200: Incident;
};

export type GetIncidentsResponse = GetIncidentsResponses[keyof GetIncidentsResponses];

export type UpdateIncidentsData = {
    body: IncidentWritable;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/incidents/{id}';
};

export type UpdateIncidentsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type UpdateIncidentsError = UpdateIncidentsErrors[keyof UpdateIncidentsErrors];

export type UpdateIncidentsResponses = {
    /**
     * OK
     */
    200: Incident;
};

export type UpdateIncidentsResponse = UpdateIncidentsResponses[keyof UpdateIncidentsResponses];

export type CreateIncidentUpdateData = {
    body: IncidentProgressWritable;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/incidents/{id}/updates';
};

export type CreateIncidentUpdateErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type CreateIncidentUpdateError = CreateIncidentUpdateErrors[keyof CreateIncidentUpdateErrors];

export type CreateIncidentUpdateResponses = {
    /**
     * OK
     */
    200: Incident;
};

export type CreateIncidentUpdateResponse = CreateIncidentUpdateResponses[keyof CreateIncidentUpdateResponses];

export type ListMaintenanceData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/maintenance';
};

export type ListMaintenanceErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ListMaintenanceError = ListMaintenanceErrors[keyof ListMaintenanceErrors];

export type ListMaintenanceResponses = {
    /**
     * OK
     */
    200: ItemsMaintenance;
};

export type ListMaintenanceResponse = ListMaintenanceResponses[keyof ListMaintenanceResponses];

export type CreateMaintenanceData = {
    body: MaintenanceWritable;
    path?: never;
    query?: never;
    url: '/api/v1/maintenance';
};

export type CreateMaintenanceErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type CreateMaintenanceError = CreateMaintenanceErrors[keyof CreateMaintenanceErrors];

export type CreateMaintenanceResponses = {
    /**
     * OK
     */
    200: Maintenance;
};

export type CreateMaintenanceResponse = CreateMaintenanceResponses[keyof CreateMaintenanceResponses];

export type DeleteMaintenanceData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/maintenance/{id}';
};

export type DeleteMaintenanceErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type DeleteMaintenanceError = DeleteMaintenanceErrors[keyof DeleteMaintenanceErrors];

export type DeleteMaintenanceResponses = {
    /**
     * OK
     */
    200: Ack;
};

export type DeleteMaintenanceResponse = DeleteMaintenanceResponses[keyof DeleteMaintenanceResponses];

export type GetMaintenanceData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/maintenance/{id}';
};

export type GetMaintenanceErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetMaintenanceError = GetMaintenanceErrors[keyof GetMaintenanceErrors];

export type GetMaintenanceResponses = {
    /**
     * OK
     */
    200: Maintenance;
};

export type GetMaintenanceResponse = GetMaintenanceResponses[keyof GetMaintenanceResponses];

export type UpdateMaintenanceData = {
    body: MaintenanceWritable;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/maintenance/{id}';
};

export type UpdateMaintenanceErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type UpdateMaintenanceError = UpdateMaintenanceErrors[keyof UpdateMaintenanceErrors];

export type UpdateMaintenanceResponses = {
    /**
     * OK
     */
    200: Maintenance;
};

export type UpdateMaintenanceResponse = UpdateMaintenanceResponses[keyof UpdateMaintenanceResponses];

export type ListMonitorsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/monitors';
};

export type ListMonitorsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ListMonitorsError = ListMonitorsErrors[keyof ListMonitorsErrors];

export type ListMonitorsResponses = {
    /**
     * OK
     */
    200: ItemsMonitor;
};

export type ListMonitorsResponse = ListMonitorsResponses[keyof ListMonitorsResponses];

export type CreateMonitorData = {
    body: MonitorWriteWritable;
    path?: never;
    query?: never;
    url: '/api/v1/monitors';
};

export type CreateMonitorErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type CreateMonitorError = CreateMonitorErrors[keyof CreateMonitorErrors];

export type CreateMonitorResponses = {
    /**
     * OK
     */
    200: Monitor;
};

export type CreateMonitorResponse = CreateMonitorResponses[keyof CreateMonitorResponses];

export type DeleteMonitorData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/monitors/{id}';
};

export type DeleteMonitorErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type DeleteMonitorError = DeleteMonitorErrors[keyof DeleteMonitorErrors];

export type DeleteMonitorResponses = {
    /**
     * OK
     */
    200: Ack;
};

export type DeleteMonitorResponse = DeleteMonitorResponses[keyof DeleteMonitorResponses];

export type GetMonitorData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/monitors/{id}';
};

export type GetMonitorErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetMonitorError = GetMonitorErrors[keyof GetMonitorErrors];

export type GetMonitorResponses = {
    /**
     * OK
     */
    200: Monitor;
};

export type GetMonitorResponse = GetMonitorResponses[keyof GetMonitorResponses];

export type UpdateMonitorData = {
    body: MonitorWriteWritable;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/monitors/{id}';
};

export type UpdateMonitorErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type UpdateMonitorError = UpdateMonitorErrors[keyof UpdateMonitorErrors];

export type UpdateMonitorResponses = {
    /**
     * OK
     */
    200: Monitor;
};

export type UpdateMonitorResponse = UpdateMonitorResponses[keyof UpdateMonitorResponses];

export type CheckMonitorData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/monitors/{id}/check';
};

export type CheckMonitorErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type CheckMonitorError = CheckMonitorErrors[keyof CheckMonitorErrors];

export type CheckMonitorResponses = {
    /**
     * Accepted
     */
    202: Ack;
};

export type CheckMonitorResponse = CheckMonitorResponses[keyof CheckMonitorResponses];

export type RotateHeartbeatData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/monitors/{id}/heartbeat/rotate';
};

export type RotateHeartbeatErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type RotateHeartbeatError = RotateHeartbeatErrors[keyof RotateHeartbeatErrors];

export type RotateHeartbeatResponses = {
    /**
     * OK
     */
    200: HeartbeatToken;
};

export type RotateHeartbeatResponse = RotateHeartbeatResponses[keyof RotateHeartbeatResponses];

export type GetMonitorHistoryData = {
    body?: never;
    path: {
        id: string;
    };
    query?: {
        from?: number;
        to?: number;
        limit?: number;
    };
    url: '/api/v1/monitors/{id}/history';
};

export type GetMonitorHistoryErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetMonitorHistoryError = GetMonitorHistoryErrors[keyof GetMonitorHistoryErrors];

export type GetMonitorHistoryResponses = {
    /**
     * OK
     */
    200: MonitorHistory;
};

export type GetMonitorHistoryResponse = GetMonitorHistoryResponses[keyof GetMonitorHistoryResponses];

export type ListPagesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/pages';
};

export type ListPagesErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ListPagesError = ListPagesErrors[keyof ListPagesErrors];

export type ListPagesResponses = {
    /**
     * OK
     */
    200: ItemsPage;
};

export type ListPagesResponse = ListPagesResponses[keyof ListPagesResponses];

export type CreatePagesData = {
    body: PageWritable;
    path?: never;
    query?: never;
    url: '/api/v1/pages';
};

export type CreatePagesErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type CreatePagesError = CreatePagesErrors[keyof CreatePagesErrors];

export type CreatePagesResponses = {
    /**
     * OK
     */
    200: Page;
};

export type CreatePagesResponse = CreatePagesResponses[keyof CreatePagesResponses];

export type DeletePagesData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/pages/{id}';
};

export type DeletePagesErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type DeletePagesError = DeletePagesErrors[keyof DeletePagesErrors];

export type DeletePagesResponses = {
    /**
     * OK
     */
    200: Ack;
};

export type DeletePagesResponse = DeletePagesResponses[keyof DeletePagesResponses];

export type GetPagesData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/pages/{id}';
};

export type GetPagesErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetPagesError = GetPagesErrors[keyof GetPagesErrors];

export type GetPagesResponses = {
    /**
     * OK
     */
    200: Page;
};

export type GetPagesResponse = GetPagesResponses[keyof GetPagesResponses];

export type UpdatePagesData = {
    body: PageWritable;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/pages/{id}';
};

export type UpdatePagesErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type UpdatePagesError = UpdatePagesErrors[keyof UpdatePagesErrors];

export type UpdatePagesResponses = {
    /**
     * OK
     */
    200: Page;
};

export type UpdatePagesResponse = UpdatePagesResponses[keyof UpdatePagesResponses];

export type PreviewPageData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/pages/{id}/preview';
};

export type PreviewPageErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type PreviewPageError = PreviewPageErrors[keyof PreviewPageErrors];

export type PreviewPageResponses = {
    /**
     * OK
     */
    200: PublicPage;
};

export type PreviewPageResponse = PreviewPageResponses[keyof PreviewPageResponses];

export type PublishPageData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/pages/{id}/publish';
};

export type PublishPageErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type PublishPageError = PublishPageErrors[keyof PublishPageErrors];

export type PublishPageResponses = {
    /**
     * OK
     */
    200: Page;
};

export type PublishPageResponse = PublishPageResponses[keyof PublishPageResponses];

export type UpdateProfileData = {
    body: ProfileWriteWritable;
    path?: never;
    query?: never;
    url: '/api/v1/profile';
};

export type UpdateProfileErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type UpdateProfileError = UpdateProfileErrors[keyof UpdateProfileErrors];

export type UpdateProfileResponses = {
    /**
     * OK
     */
    200: User;
};

export type UpdateProfileResponse = UpdateProfileResponses[keyof UpdateProfileResponses];

export type ListSecretsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/secrets';
};

export type ListSecretsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ListSecretsError = ListSecretsErrors[keyof ListSecretsErrors];

export type ListSecretsResponses = {
    /**
     * OK
     */
    200: ItemsSecret;
};

export type ListSecretsResponse = ListSecretsResponses[keyof ListSecretsResponses];

export type CreateSecretData = {
    body: SecretWriteWritable;
    path?: never;
    query?: never;
    url: '/api/v1/secrets';
};

export type CreateSecretErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type CreateSecretError = CreateSecretErrors[keyof CreateSecretErrors];

export type CreateSecretResponses = {
    /**
     * OK
     */
    200: Secret;
};

export type CreateSecretResponse = CreateSecretResponses[keyof CreateSecretResponses];

export type DeleteSecretData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/secrets/{id}';
};

export type DeleteSecretErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type DeleteSecretError = DeleteSecretErrors[keyof DeleteSecretErrors];

export type DeleteSecretResponses = {
    /**
     * OK
     */
    200: Ack;
};

export type DeleteSecretResponse = DeleteSecretResponses[keyof DeleteSecretResponses];

export type UpdateSecretData = {
    body: SecretWriteWritable;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/secrets/{id}';
};

export type UpdateSecretErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type UpdateSecretError = UpdateSecretErrors[keyof UpdateSecretErrors];

export type UpdateSecretResponses = {
    /**
     * OK
     */
    200: Secret;
};

export type UpdateSecretResponse = UpdateSecretResponses[keyof UpdateSecretResponses];

export type DeleteSessionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/session';
};

export type DeleteSessionErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type DeleteSessionError = DeleteSessionErrors[keyof DeleteSessionErrors];

export type DeleteSessionResponses = {
    /**
     * OK
     */
    200: {
        csrfToken: string;
        user: User | null;
    };
};

export type DeleteSessionResponse = DeleteSessionResponses[keyof DeleteSessionResponses];

export type GetSessionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/session';
};

export type GetSessionErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetSessionError = GetSessionErrors[keyof GetSessionErrors];

export type GetSessionResponses = {
    /**
     * OK
     */
    200: {
        csrfToken: string;
        user: User | null;
    };
};

export type GetSessionResponse = GetSessionResponses[keyof GetSessionResponses];

export type CreateSessionData = {
    body: CredentialsWritable;
    path?: never;
    query?: never;
    url: '/api/v1/session';
};

export type CreateSessionErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type CreateSessionError = CreateSessionErrors[keyof CreateSessionErrors];

export type CreateSessionResponses = {
    /**
     * OK
     */
    200: {
        csrfToken: string;
        user: User | null;
    };
};

export type CreateSessionResponse = CreateSessionResponses[keyof CreateSessionResponses];

export type GetSettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/settings';
};

export type GetSettingsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetSettingsError = GetSettingsErrors[keyof GetSettingsErrors];

export type GetSettingsResponses = {
    /**
     * OK
     */
    200: Settings;
};

export type GetSettingsResponse = GetSettingsResponses[keyof GetSettingsResponses];

export type UpdateSettingsData = {
    body: SettingsWritable;
    path?: never;
    query?: never;
    url: '/api/v1/settings';
};

export type UpdateSettingsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type UpdateSettingsError = UpdateSettingsErrors[keyof UpdateSettingsErrors];

export type UpdateSettingsResponses = {
    /**
     * OK
     */
    200: Settings;
};

export type UpdateSettingsResponse = UpdateSettingsResponses[keyof UpdateSettingsResponses];

export type GetSetupData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/setup';
};

export type GetSetupErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetSetupError = GetSetupErrors[keyof GetSetupErrors];

export type GetSetupResponses = {
    /**
     * OK
     */
    200: SetupStatus;
};

export type GetSetupResponse = GetSetupResponses[keyof GetSetupResponses];

export type CreateSetupData = {
    body: SetupBodyWritable;
    path?: never;
    query?: never;
    url: '/api/v1/setup';
};

export type CreateSetupErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type CreateSetupError = CreateSetupErrors[keyof CreateSetupErrors];

export type CreateSetupResponses = {
    /**
     * OK
     */
    200: {
        csrfToken: string;
        user: User | null;
    };
};

export type CreateSetupResponse = CreateSetupResponses[keyof CreateSetupResponses];

export type ListUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users';
};

export type ListUsersErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ListUsersError = ListUsersErrors[keyof ListUsersErrors];

export type ListUsersResponses = {
    /**
     * OK
     */
    200: ItemsUser;
};

export type ListUsersResponse = ListUsersResponses[keyof ListUsersResponses];

export type CreateUserData = {
    body: UserWriteWritable;
    path?: never;
    query?: never;
    url: '/api/v1/users';
};

export type CreateUserErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type CreateUserError = CreateUserErrors[keyof CreateUserErrors];

export type CreateUserResponses = {
    /**
     * OK
     */
    200: User;
};

export type CreateUserResponse = CreateUserResponses[keyof CreateUserResponses];

export type DeleteUserData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/users/{id}';
};

export type DeleteUserErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type DeleteUserError = DeleteUserErrors[keyof DeleteUserErrors];

export type DeleteUserResponses = {
    /**
     * OK
     */
    200: Ack;
};

export type DeleteUserResponse = DeleteUserResponses[keyof DeleteUserResponses];

export type UpdateUserData = {
    body: UserWriteWritable;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/users/{id}';
};

export type UpdateUserErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type UpdateUserError = UpdateUserErrors[keyof UpdateUserErrors];

export type UpdateUserResponses = {
    /**
     * OK
     */
    200: User;
};

export type UpdateUserResponse = UpdateUserResponses[keyof UpdateUserResponses];
