/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/[[slug]]/[[...rest]]+': RouteRecordInfo<
      '/[[slug]]/[[...rest]]+',
      '/:slug?/:rest(.*)*',
      { rest?: ParamValueZeroOrMore<true>, slug?: ParamValueZeroOrOne<true> },
      { rest?: ParamValueZeroOrMore<false>, slug?: ParamValueZeroOrOne<false> },
      | never
    >,
    '/app/(admin)': RouteRecordInfo<
      '/app/(admin)',
      '/app',
      Record<never, never>,
      Record<never, never>,
      | '/app/(admin)/'
      | '/app/(admin)/audit'
      | '/app/(admin)/incidents'
      | '/app/(admin)/maintenance'
      | '/app/(admin)/monitors/'
      | '/app/(admin)/monitors/[id]/'
      | '/app/(admin)/monitors/[id]/edit'
      | '/app/(admin)/monitors/new'
      | '/app/(admin)/notifications'
      | '/app/(admin)/pages/'
      | '/app/(admin)/pages/[id]'
      | '/app/(admin)/pages/new'
      | '/app/(admin)/secrets'
      | '/app/(admin)/servers'
      | '/app/(admin)/settings'
      | '/app/(admin)/users'
    >,
    '/app/(admin)/': RouteRecordInfo<
      '/app/(admin)/',
      '/app',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/app/(admin)/audit': RouteRecordInfo<
      '/app/(admin)/audit',
      '/app/audit',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/app/(admin)/incidents': RouteRecordInfo<
      '/app/(admin)/incidents',
      '/app/incidents',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/app/(admin)/maintenance': RouteRecordInfo<
      '/app/(admin)/maintenance',
      '/app/maintenance',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/app/(admin)/monitors/': RouteRecordInfo<
      '/app/(admin)/monitors/',
      '/app/monitors',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/app/(admin)/monitors/[id]/': RouteRecordInfo<
      '/app/(admin)/monitors/[id]/',
      '/app/monitors/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/app/(admin)/monitors/[id]/edit': RouteRecordInfo<
      '/app/(admin)/monitors/[id]/edit',
      '/app/monitors/:id/edit',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/app/(admin)/monitors/new': RouteRecordInfo<
      '/app/(admin)/monitors/new',
      '/app/monitors/new',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/app/(admin)/notifications': RouteRecordInfo<
      '/app/(admin)/notifications',
      '/app/notifications',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/app/(admin)/pages/': RouteRecordInfo<
      '/app/(admin)/pages/',
      '/app/pages',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/app/(admin)/pages/[id]': RouteRecordInfo<
      '/app/(admin)/pages/[id]',
      '/app/pages/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/app/(admin)/pages/new': RouteRecordInfo<
      '/app/(admin)/pages/new',
      '/app/pages/new',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/app/(admin)/secrets': RouteRecordInfo<
      '/app/(admin)/secrets',
      '/app/secrets',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/app/(admin)/servers': RouteRecordInfo<
      '/app/(admin)/servers',
      '/app/servers',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/app/(admin)/settings': RouteRecordInfo<
      '/app/(admin)/settings',
      '/app/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/app/(admin)/users': RouteRecordInfo<
      '/app/(admin)/users',
      '/app/users',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/app/login': RouteRecordInfo<
      '/app/login',
      '/app/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/[[slug]]/[[...rest]]+.vue': {
      routes:
        | '/[[slug]]/[[...rest]]+'
      views:
        | never
      pathParamNames:
        | 'rest'
    }
    'src/pages/app/(admin).vue': {
      routes:
        | '/app/(admin)'
        | '/app/(admin)/'
        | '/app/(admin)/audit'
        | '/app/(admin)/incidents'
        | '/app/(admin)/maintenance'
        | '/app/(admin)/monitors/'
        | '/app/(admin)/monitors/[id]/'
        | '/app/(admin)/monitors/[id]/edit'
        | '/app/(admin)/monitors/new'
        | '/app/(admin)/notifications'
        | '/app/(admin)/pages/'
        | '/app/(admin)/pages/[id]'
        | '/app/(admin)/pages/new'
        | '/app/(admin)/secrets'
        | '/app/(admin)/servers'
        | '/app/(admin)/settings'
        | '/app/(admin)/users'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/app/(admin)/index.vue': {
      routes:
        | '/app/(admin)/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/app/(admin)/audit.vue': {
      routes:
        | '/app/(admin)/audit'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/app/(admin)/incidents.vue': {
      routes:
        | '/app/(admin)/incidents'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/app/(admin)/maintenance.vue': {
      routes:
        | '/app/(admin)/maintenance'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/app/(admin)/monitors/index.vue': {
      routes:
        | '/app/(admin)/monitors/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/app/(admin)/monitors/[id]/index.vue': {
      routes:
        | '/app/(admin)/monitors/[id]/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/app/(admin)/monitors/[id]/edit.vue': {
      routes:
        | '/app/(admin)/monitors/[id]/edit'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/app/(admin)/monitors/new.vue': {
      routes:
        | '/app/(admin)/monitors/new'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/app/(admin)/notifications.vue': {
      routes:
        | '/app/(admin)/notifications'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/app/(admin)/pages/index.vue': {
      routes:
        | '/app/(admin)/pages/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/app/(admin)/pages/[id].vue': {
      routes:
        | '/app/(admin)/pages/[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/app/(admin)/pages/new.vue': {
      routes:
        | '/app/(admin)/pages/new'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/app/(admin)/secrets.vue': {
      routes:
        | '/app/(admin)/secrets'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/app/(admin)/servers.vue': {
      routes:
        | '/app/(admin)/servers'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/app/(admin)/settings.vue': {
      routes:
        | '/app/(admin)/settings'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/app/(admin)/users.vue': {
      routes:
        | '/app/(admin)/users'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/app/login.vue': {
      routes:
        | '/app/login'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
